# Generated by Django 5.1.15 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sales", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cancelled_cash_movement",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cancelled_sale", to="cash.cashmovement"),
        ),
        migrations.AddField(
            model_name="sale",
            name="cancelled_inventory_movement",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cancelled_sale", to="inventory.inventorymovement"),
        ),
    ]