# Generated by Django 5.1.15 on 2026-08-26 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_migrate_user_assignments'),
        ('cash', '0003_alter_cashmovement_options_and_more'),
        ('sales', '0002_sale_cancellation_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='monto original')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='saldo pendiente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Pago parcial'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15, verbose_name='estado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='branches.branch', verbose_name='sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='sales.sale', verbose_name='venta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_credits', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'crédito',
                'verbose_name_plural': 'créditos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='monto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observación')),
                ('cash_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payment', to='cash.cashmovement', verbose_name='movimiento de caja')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='cash.cashregister', verbose_name='caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.credit', verbose_name='crédito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_credit_payments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pago de crédito',
                'verbose_name_plural': 'pagos de créditos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('id_document', models.CharField(max_length=30, unique=True, verbose_name='documento de identidad')),
                ('tax_id', models.CharField(blank=True, default='', max_length=30, verbose_name='NIT')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='dirección')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='customers.customer', verbose_name='cliente'),
        ),
    ]
