# Generated by Django 5.1.15 on 2026-08-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_migrate_user_assignments'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'traspaso', 'verbose_name_plural': 'traspasos'},
        ),
        migrations.AlterModelOptions(
            name='transferitem',
            options={'verbose_name': 'detalle de traspaso', 'verbose_name_plural': 'detalles de traspaso'},
        ),
        migrations.AlterField(
            model_name='transfer',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='branches.branch', verbose_name='sucursal destino'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observación'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='origin_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='branches.branch', verbose_name='sucursal origen'),
        ),
    ]
