# Generated by Django 5.1.15 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="branches.branch",
                verbose_name="sucursal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadministrador"),
                    ("admin", "Administrador"),
                    ("cajero", "Cajero"),
                    ("almacenero", "Almacenero"),
                ],
                default="superadmin",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]