# Generated by Django 5.1.15 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0003_migrate_user_assignments"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="existencia")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="branches.branch", verbose_name="sucursal")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="products.product", verbose_name="producto")),
            ],
            options={"verbose_name": "existencia", "verbose_name_plural": "existencias", "ordering": ["branch__name", "product__name"]},
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(fields=("product", "branch"), name="unique_stock_per_product_branch"),
        ),
    ]