# Generated by Django 5.1.15 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement_type", models.CharField(choices=[("ENTRY", "Entrada"), ("OUTPUT", "Salida"), ("TRANSFER", "Traspaso"), ("ADJUSTMENT", "Ajuste")], max_length=20, verbose_name="tipo")),
                ("status", models.CharField(choices=[("DRAFT", "Borrador"), ("POSTED", "Confirmado")], default="DRAFT", max_length=10, verbose_name="estado")),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_movements", to="branches.branch", verbose_name="sucursal")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "movimiento de inventario", "verbose_name_plural": "movimientos de inventario", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="InventoryMovementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="cantidad")),
                ("adjustment_direction", models.CharField(blank=True, choices=[("ENTRY", "Aumentar"), ("OUTPUT", "Disminuir")], max_length=10, verbose_name="dirección del ajuste")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("movement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.inventorymovement", verbose_name="movimiento")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_movement_lines", to="products.product", verbose_name="producto")),
            ],
            options={"verbose_name": "línea de movimiento", "verbose_name_plural": "líneas de movimiento"},
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["branch", "-created_at"], name="inventory_i_branch__b30623_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorymovementline",
            constraint=models.UniqueConstraint(fields=("movement", "product"), name="unique_product_per_inventory_movement"),
        ),
    ]