# Generated by Django 5.1.15 on 2026-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_movement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_branch__305656_idx',
            old_name='inventory_i_branch__b30623_idx',
        ),
    ]
