# Generated by Django 5.1.15 on 2026-09-23 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_i_branch__b30623_idx_inventory_i_branch__305656_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='movement_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha'),
        ),
    ]
