# Generated by Django 5.1.15 on 2026-08-25

from django.db import migrations


ROLE_MAPPING = {
    "admin": "admin",
    "cashier": "cajero",
    "stock_manager": "almacenero",
}


def migrate_user_assignments(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserBranch = apps.get_model("branches", "UserBranch")

    for assignment in UserBranch.objects.order_by("user_id", "-is_default", "id"):
        role = ROLE_MAPPING.get(assignment.role)
        if role:
            User.objects.filter(pk=assignment.user_id, branch__isnull=True).update(
                branch_id=assignment.branch_id,
                role=role,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_initial"),
        ("users", "0002_user_branch_user_role"),
    ]

    operations = [
        migrations.RunPython(migrate_user_assignments, migrations.RunPython.noop),
        migrations.DeleteModel(name="UserBranch"),
    ]