# Generated by Django 5.1.15 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cash", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.RemoveField(model_name="cashregister", name="shift"),
        migrations.DeleteModel(name="Shift"),
        migrations.AddField(model_name="cashregister", name="expected_amount", field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
        migrations.AddField(model_name="cashregister", name="difference", field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
        migrations.AlterField(model_name="cashmovement", name="movement_type", field=models.CharField(choices=[("OPENING", "Apertura"), ("SALE", "Venta"), ("CREDIT_COLLECTION", "Cobro de crédito"), ("PETTY_CASH_EXPENSE", "Gasto de caja chica"), ("SMALL_PURCHASE", "Compra menor"), ("TRAVEL_EXPENSE", "Viático"), ("ADJUSTMENT", "Ajuste"), ("REFUND", "Devolución"), ("CLOSING", "Cierre")], max_length=20)),
        migrations.CreateModel(name="ExpenseCategory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=100, unique=True)), ("is_active", models.BooleanField(default=True)), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="PettyCashExpense", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("concept", models.CharField(max_length=255)), ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])), ("cash_register", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="petty_cash_expenses", to="cash.cashregister")), ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="cash.expensecategory")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)), ("movement", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="petty_cash_expense", to="cash.cashmovement")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="petty_cash_expenses", to=settings.AUTH_USER_MODEL))]),
    ]