# Generated by Django 5.1.15 on 2026-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_remove_shift_add_petty_cash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'movimiento de caja', 'verbose_name_plural': 'movimientos de caja'},
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-opened_at'], 'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'categoría de gasto', 'verbose_name_plural': 'categorías de gasto'},
        ),
        migrations.AlterModelOptions(
            name='pettycashexpense',
            options={'ordering': ['-created_at'], 'verbose_name': 'gasto de caja chica', 'verbose_name_plural': 'gastos de caja chica'},
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='cash_cashmo_cash_re_b2c17d_idx',
            old_name='cash_cashr_registe_5236bc_idx',
        ),
    ]
